language: java
jdk: oraclejdk8
sudo: true
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
before_script: ./bin/before_build.sh
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: ./gradlew check -i -s
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
