dist: bionic
sudo: required

language: java
jdk:
  - openjdk11

notifications:
  email:
    - michael@rabbitmq.com
    - acogoluegnes@vmware.com
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:23.1-1
branches:
  only:
    - master
env:
  - HOP_RABBITMQCTL=rabbitmq/sbin/rabbitmqctl HOP_RABBITMQ_PLUGINS=rabbitmq/sbin/rabbitmq-plugins
before_script:
  - ./bin/set_up_infra.sh
  - ./bin/before_build.sh

script: ./mvnw clean test
cache:
  directories:
    - $HOME/.m2
install: true
